// Purpose: to create a list of paintings to be used in the auction
const PaintingList = [
  {
    id: '1',
    title: 'Painting',
    description: 'Painting by Picasso',
    startingPrice: 1000,
    currentPrice: 1000,
    image: 'https://www.pablopicasso.org/images/paintings/the-weeping-woman.jpg',
    status: 'ACTIVE',
  },
  {
    id: '2',
    title: 'Painting',
    description: 'Painting by Van Gogh',
    startingPrice: 2000,
    currentPrice: 2000,
    image: 'https://www.vangoghgallery.com/img/starry_night_full.jpg',
    status: 'ACTIVE',
  },
  {
    id: '3',
    title: 'Painting',
    description: 'Painting by Monet',
    startingPrice: 3000,
    currentPrice: 3000,
    image: 'https://www.monetpaintings.org/images/paintings/water-lilies-1916.jpg',
    status: 'ACTIVE',
  },
  {
    id: '4',
    title: 'Painting',
    description: 'Painting by Rembrandt',
    startingPrice: 4000,
    currentPrice: 4000,
    image: 'https://www.rembrandtpainting.net/images/paintings/the-night-watch.jpg',
    status: 'ACTIVE',
  },
  {
    id: '5',
    title: 'Painting',
    description: 'Painting by Da Vinci',
    startingPrice: 5000,
    currentPrice: 5000,
    image: 'https://www.leonardodavinci.net/images/paintings/the-last-supper.jpg',
    status: 'ACTIVE',
  },
  {
    id: '6',
    title: 'Painting',
    description: 'Painting by Michelangelo',
    startingPrice: 6000,
    currentPrice: 6000,
    image: 'https://www.michelangelo.net/images/paintings/the-creation-of-adam.jpg',
    status: 'ACTIVE',
  },
  {
    id: '7',
    title: 'Painting',
    description: 'Painting by Raphael',
    startingPrice: 7000,
    currentPrice: 7000,
    image: 'https://www.raphaelpaintings.org/images/paintings/the-school-of-athens.jpg',
    status: 'ACTIVE',
  },
  {
    id: '8',
    title: 'Painting',
    description: 'Painting by Botticelli',
    startingPrice: 8000,
    currentPrice: 8000,
    image: 'https://www.sandro-botticelli.net/images/paintings/the-birth-of-venus.jpg',
    status: 'ACTIVE',
  },
  {
    id: '9',
    title: 'Painting',
    description: 'Painting by Munch',
    startingPrice: 9000,
    currentPrice: 9000,
    image: 'https://www.edvardmunch.org/images/paintings/the-scream.jpg',
    status: 'ACTIVE',
  },
  {
    id: '10',
    title: 'Painting',
    description: 'Painting by Klimt',
    startingPrice: 10000,
    currentPrice: 10000,
    image: 'https://www.gustav-klimt.com/images/paintings/the-kiss.jpg',
    status: 'ACTIVE',
  },
  {
    id: '11',
    title: 'Painting',
    description: 'Painting by Dali',
    startingPrice: 11000,
    currentPrice: 11000,
    image: 'https://www.salvadordalipaintings.org/images/paintings/the-persistence-of-memory.jpg',
    status: 'ACTIVE',
  },
  {
    id: '12',
    title: 'Painting',
    description: 'Painting by Vermeer',
    startingPrice: 12000,
    currentPrice: 12000,
    image: 'https://www.essentialvermeer.com/images/paintings/girl-with-a-pearl-earring.jpg',
    status: 'ACTIVE',
  },
  {
    id: '13',
    title: 'Painting',
    description: 'Painting by Cézanne',
    startingPrice: 13000,
    currentPrice: 13000,
    image: 'https://www.paul-cezanne.org/images/paintings/mont-sainte-victoire.jpg',
    status: 'ACTIVE',
  },
  {
    id: '14',
    title: 'Painting',
    description: 'Painting by Turner',
    startingPrice: 14000,
    currentPrice: 14000,
    image: 'https://www.jmwturner.org/images/paintings/the-fighting-temeraire.jpg',
    status: 'ACTIVE',
  },
  {
    id: '15',
    title: 'Painting',
    description: 'Painting by Renoir',
    startingPrice: 15000,
    currentPrice: 15000,
    image: 'https://www.pierre-auguste-renoir.org/images/paintings/luncheon-of-the-boating-party.jpg',
    status: 'ACTIVE',
  },
  {
    id: '16',
    title: 'Painting',
    description: 'Painting by Hopper',
    startingPrice: 16000,
    currentPrice: 16000,
    image: 'https://www.edwardhopper.net/images/paintings/nighthawks.jpg',
    status: 'ACTIVE',
  },
  {
    id: '17',
    title: 'Painting',
    description: 'Painting by Warhol',
    startingPrice: 17000,
    currentPrice: 17000,
    image: 'https://www.warholprints.com/images/paintings/marilyn-diptych.jpg',
    status: 'ACTIVE',
  },
  {
    id: '18',
    title: 'Painting',
    description: 'Painting by Kahlo',
    startingPrice: 18000,
    currentPrice: 18000,
    image: 'https://www.fridakahlo.org/images/paintings/the-two-fridas.jpg',
    status: 'ACTIVE',
  },
  {
    id: '19',
    title: 'Painting',
    description: 'Painting by Basquiat',
    startingPrice: 19000,
    currentPrice: 19000,
    image: 'https://www.jean-michel-basquiat.org/images/paintings/untitled-skull.jpg',
    status: 'ACTIVE',
  },
  {
    id: '20',
    title: 'Painting',
    description: 'Painting by Kandinsky',
    startingPrice: 20000,
    currentPrice: 20000,
    image: 'https://www.wassilykandinsky.net/images/paintings/comp-9.jpg',
    status: 'ACTIVE',
  },
  {
    id: '21',
    title: 'Painting',
    description: 'Painting by Frida',
    startingPrice: 21000,
    currentPrice: 21000,
    image: 'https://www.frida.org/images/paintings/self-portrait-with-thorn-necklace-and-hummingbird.jpg',
    status: 'ACTIVE',
  },
  {
    id: '22',
    title: 'Painting',
    description: 'Painting by Pollock',
    startingPrice: 22000,
    currentPrice: 22000,
    image: 'https://www.jackson-pollock.org/images/paintings/number-1-lavender-mist.jpg',
    status: 'ACTIVE',
  },
  {
    id: '23',
    title: 'Painting',
    description: 'Painting by Rothko',
    startingPrice: 23000,
    currentPrice: 23000,
    image: 'https://www.markrothko.org/images/paintings/no-14.jpg',
    status: 'ACTIVE',
  },
  {
    id: '24',
    title: 'Painting',
    description: 'Painting by Degas',
    startingPrice: 24000,
    currentPrice: 24000,
    image: 'https://www.edgar-degas.org/images/paintings/the-dance-class.jpg',
    status: 'ACTIVE',
  },
  {
    id: '25',
    title: 'Painting',
    description: 'Painting by OKeeffe',
    startingPrice: 25000,
    currentPrice: 25000,
    image: 'https://www.georgiaokeeffe.net/images/paintings/jack-in-the-pulpit-no-iv.jpg',
    status: 'ACTIVE',
  },
  {
    id: '26',
    title: 'Painting',
    description: 'Painting by Magritte',
    startingPrice: 26000,
    currentPrice: 26000,
    image: 'https://www.rene-magritte.org/images/paintings/the-son-of-man.jpg',
    status: 'ACTIVE',
  },
  {
    id: '27',
    title: 'Painting',
    description: 'Painting by Hockney',
    startingPrice: 27000,
    currentPrice: 27000,
    image: 'https://www.davidhockney.net/images/paintings/a-bigger-splash.jpg',
    status: 'ACTIVE',
  },
  {
    id: '28',
    title: 'Painting',
    description: 'Painting by Caillebotte',
    startingPrice: 28000,
    currentPrice: 28000,
    image: 'https://www.gustavcaillebotte.org/images/paintings/paris-street-rainy-day.jpg',
    status: 'ACTIVE',
  },
  {
    id: '29',
    title: 'Painting',
    description: 'Painting by Gauguin',
    startingPrice: 29000,
    currentPrice: 29000,
    image: 'https://www.paul-gauguin.net/images/paintings/where-do-we-come-from-what-are-we-where-are-we-going.jpg',
    status: 'ACTIVE',
  },
  {
    id: '30',
    title: 'Painting',
    description: 'Painting by Seurat',
    startingPrice: 30000,
    currentPrice: 30000,
    image: 'https://www.georgesseurat.org/images/paintings/a-sunday-afternoon-on-the-island-of-la-grande-jatte.jpg',
    status: 'ACTIVE',
  },
  {
    id: '31',
    title: 'Painting',
    description: 'Painting by Chagall',
    startingPrice: 31000,
    currentPrice: 31000,
    image: 'https://www.marc-chagall.net/images/paintings/i-and-the-village.jpg',
    status: 'ACTIVE',
  },
  {
    id: '32',
    title: 'Painting',
    description: 'Painting by Hokusai',
    startingPrice: 32000,
    currentPrice: 32000,
    image: 'https://www.katsushika-hokusai.org/images/paintings/the-great-wave-off-kanagawa.jpg',
    status: 'ACTIVE',
  },
  {
    id: '33',
    title: 'Painting',
    description: 'Painting by Van Eyck',
    startingPrice: 33000,
    currentPrice: 33000,
    image: 'https://www.hubert-van-eyck.org/images/paintings/the-arnolfini-portrait.jpg',
    status: 'ACTIVE',
  },
  {
    id: '34',
    title: 'Painting',
    description: 'Painting by Veronese',
    startingPrice: 34000,
    currentPrice: 34000,
    image: 'https://www.paolo-veronese.org/images/paintings/the-wedding-at-cana.jpg',
    status: 'ACTIVE',
  },
  {
    id: '35',
    title: 'Painting',
    description: 'Painting by Titian',
    startingPrice: 35000,
    currentPrice: 35000,
    image: 'https://www.tizianovecellio.org/images/paintings/venus-of-urbino.jpg',
    status: 'ACTIVE',
  },
  {
    id: '36',
    title: 'Painting',
    description: 'Painting by Caravaggio',
    startingPrice: 36000,
    currentPrice: 36000,
    image: 'https://www.caravaggio.net/images/paintings/the-calling-of-saint-matthew.jpg',
    status: 'ACTIVE',
  },
  {
    id: '37',
    title: 'Painting',
    description: 'Painting by Velázquez',
    startingPrice: 37000,
    currentPrice: 37000,
    image: 'https://www.diego-velazquez.org/images/paintings/las-meninas.jpg',
    status: 'ACTIVE',
  },
  {
    id: '38',
    title: 'Painting',
    description: 'Painting by El Greco',
    startingPrice: 38000,
    currentPrice: 38000,
    image: 'https://www.el-greco.org/images/paintings/the-burial-of-the-count-of-orgaz.jpg',
    status: 'ACTIVE',
  },
  {
    id: '39',
    title: 'Painting',
    description: 'Painting by Goya',
    startingPrice: 39000,
    currentPrice: 39000,
    image: 'https://www.francisco-goya.org/images/paintings/saturn-devouring-his-son.jpg',
    status: 'ACTIVE',
  },
  {
    id: '40',
    title: 'Painting',
    description: 'Painting by Bosch',
    startingPrice: 40000,
    currentPrice: 40000,
    image: 'https://www.hieronymus-bosch.org/images/paintings/the-garden-of-earthly-delights.jpg',
    status: 'ACTIVE',
  },
  {
    id: '41',
    title: 'Painting',
    description: 'Painting by Klee',
    startingPrice: 41000,
    currentPrice: 41000,
    image: 'https://www.paul-klee.org/images/paintings/twittering-machine.jpg',
    status: 'ACTIVE',
  },
  {
    id: '42',
    title: 'Painting',
    description: 'Painting by Mondrian',
    startingPrice: 42000,
    currentPrice: 42000,
    image: 'https://www.piet-mondrian.org/images/paintings/composition-with-red-blue-and-yellow.jpg',
    status: 'ACTIVE',
  },
  {
    id: '43',
    title: 'Painting',
    description: 'Painting by Rousseau',
    startingPrice: 43000,
    currentPrice: 43000,
    image: 'https://www.henri-rousseau.org/images/paintings/the-sleeping-gypsy.jpg',
    status: 'ACTIVE',
  },
  {
    id: '44',
    title: 'Painting',
    description: 'Painting by Magritte',
    startingPrice: 44000,
    currentPrice: 44000,
    image: 'https://www.rene-magritte.org/images/paintings/the-son-of-man.jpg',
    status: 'ACTIVE',
  },
  {
    id: '45',
    title: 'Painting',
    description: 'Painting by Hockney',
    startingPrice: 45000,
    currentPrice: 45000,
    image: 'https://www.davidhockney.net/images/paintings/a-bigger-splash.jpg',
    status: 'ACTIVE',
  },
  {
    id: '46',
    title: 'Painting',
    description: 'Painting by Caillebotte',
    startingPrice: 46000,
    currentPrice: 46000,
    image: 'https://www.gustavcaillebotte.org/images/paintings/paris-street-rainy-day.jpg',
    status: 'ACTIVE',
  },
  {
    id: '47',
    title: 'Painting',
    description: 'Painting by Gauguin',
    startingPrice: 47000,
    currentPrice: 47000,
    image: 'https://www.paul-gauguin.net/images/paintings/where-do-we-come-from-what-are-we-where-are-we-going.jpg',
    status: 'ACTIVE',
  },
  {
    id: '48',
    title: 'Painting',
    description: 'Painting by Seurat',
    startingPrice: 48000,
    currentPrice: 48000,
    image: 'https://www.georgesseurat.org/images/paintings/a-sunday-afternoon-on-the-island-of-la-grande-jatte.jpg',
    status: 'ACTIVE',
  },
  {
    id: '49',
    title: 'Painting',
    description: 'Painting by Frida',
    startingPrice: 49000,
    currentPrice: 49000,
    image: 'https://www.frida.org/images/paintings/self-portrait-with-thorn-necklace-and-hummingbird.jpg',
    status: 'ACTIVE',
  },
  {
    id: '50',
    title: 'Painting',
    description: 'Painting by Pollock',
    startingPrice: 50000,
    currentPrice: 50000,
    image: 'https://www.jackson-pollock.org/images/paintings/number-1-lavender-mist.jpg',
    status: 'ACTIVE',
  },
];



  
const FountainPens = [
  {
    id: '1',
    brand: 'Montblanc',
    model: 'Meisterstück 149',
    description: 'Iconic fountain pen with gold accents',
    price: 1000,
    nibSize: 'Medium',
    startingPrice: 1000,
    currentPrice: 1000,
    image: 'https://www.montblanc.com/variation-image/7085/7085.webp',
    status: 'ACTIVE',
  },
  {
    id: '2',
    brand: 'Pelikan',
    model: 'M800 Souverän',
    description: 'Elegant piston-filler with gold nib',
    price: 800,
    nibSize: 'Fine',
    startingPrice: 800,
    currentPrice: 800,
    image:
      'https://www.pelikan.com/pulse/Pulsar/en_US.Store.displayImage.223438/pelikan-m800-pistong-fountain-pen.jpg',
    status: 'ACTIVE',
  },
  {
    id: '3',
    brand: 'Namiki',
    model: 'Emperor',
    description: 'Masterfully crafted large-sized pen',
    price: 5000,
    nibSize: 'Broad',
    startingPrice: 5000,
    currentPrice: 5000,
    image: 'https://www.pilot.co.jp/products/pen/fountain/emperor/img/emperor.jpg',
    status: 'ACTIVE',
  },
  {
    id: '4',
    brand: 'Visconti',
    model: 'Homo Sapiens',
    description: 'Unique pen made from volcanic lava',
    price: 1200,
    nibSize: 'Medium',
    startingPrice: 1200,
    currentPrice: 1200,
    image: 'https://www.visconti.it/media/catalog/product/cache/3/image/9df78eab33525d08d6e5fb8d27136e95/h/o/homo_sapiens_brilliant.jpg',
    status: 'ACTIVE',
  },
  {
    id: '5',
    brand: 'S.T. Dupont',
    model: 'Line D',
    description: 'Refined pen with guilloche patterns',
    price: 900,
    nibSize: 'Fine',
    startingPrice: 900,
    currentPrice: 900,
    image: 'https://www.st-dupont.com/dw/image/v2/BBVX_PRD/on/demandware.static/-/Sites-master-catalog/en_US/dwdf7812f2/images/products/410674m.jpg',
    status: 'ACTIVE',
  },
  {
    id: '6',
    brand: 'Aurora',
    model: 'Optima',
    description: 'Elegant resin-bodied pen with gold trim',
    price: 600,
    nibSize: 'Medium',
    startingPrice: 600,
    currentPrice: 600,
    image: 'https://www.aurorapen.it/uploads/2021/prodotti/p_4c2cb8c6e95d14b0f15df8f9254fb0b2.png',
    status: 'ACTIVE',
  },
  {
    id: '7',
    brand: 'Waterman',
    model: 'Carene',
    description: 'Streamlined pen with silver accents',
    price: 400,
    nibSize: 'Fine',
    startingPrice: 400,
    currentPrice: 400,
    image: 'https://www.waterman.com/pub/media/catalog/product/c/a/carene_rollerball.jpg',
    status: 'ACTIVE',
  },
  {
    id: '8',
    brand: 'Parker',
    model: 'Duofold Centennial',
    description: 'Classic design with gold-plated trim',
    price: 700,
    nibSize: 'Medium',
    startingPrice: 700,
    currentPrice: 700,
    image: 'https://www.parkerpen.com/-/media/parker-pens/images/products/catalog/duofold/duofold-black-gt-m.jpg',
    status: 'ACTIVE',
  },
  {
    id: '9',
    brand: 'Caran d\'Ache',
    model: 'Léman',
    description: 'Luxurious pen with lacquered body',
    price: 800,
    nibSize: 'Broad',
    startingPrice: 800,
    currentPrice: 800,
    image: 'https://www.carandache.com/media/catalog/product/cache/1/image/1000x1000/af267278c1fc4c7d31267e2edbef642d/8/1/8492.498.jpg',
    status: 'ACTIVE',
  },
  {
    id: '10',
    brand: 'Omas',
    model: 'Arte Italiana',
    description: 'Handcrafted pen with celluloid body',
    price: 1500,
    nibSize: 'Fine',
    startingPrice: 1500,
    currentPrice: 1500,
    image: 'https://www.omas.com/media/catalog/product/cache/2/thumbnail/9df78eab33525d08d6e5fb8d27136e95/7/3/73-1583700337.jpg',
    status: 'ACTIVE',
  },
  {
    id: '11',
    brand: 'Pilot',
    model: 'Custom 823',
    description: 'Vacuum-filling demonstrator pen',
    price: 300,
    nibSize: 'Medium',
    startingPrice: 300,
    currentPrice: 300,
    image: 'https://www.pilot.co.jp/products/pen/fountain/custom/img/custom823_clear.jpg',
    status: 'ACTIVE',
  },
  {
    id: '12',
    brand: 'Lamy',
    model: 'Safari',
    description: 'Durable pen with a classic design',
    price: 50,
    nibSize: 'Extra Fine',
    startingPrice: 50,
    currentPrice: 50,
    image: 'https://www.lamy.com/content/lamy_com/en/home/products/writing-instruments/fountain-pens/lamy-safari/1200x630/safari_black_07.png',
    status: 'ACTIVE',
  },
  {
    id: '13',
    brand: 'TWSBI',
    model: 'Eco',
    description: 'Affordable piston-filling demonstrator pen',
    price: 30,
    nibSize: 'Fine',
    startingPrice: 30,
    currentPrice: 30,
    image: 'https://www.twsbi.com/bbs/board.php?bo_table=products&wr_id=32',
    status: 'ACTIVE',
  },
  {
    id: '14',
    brand: 'Pilot',
    model: 'Vanishing Point',
    description: 'Retractable fountain pen with click mechanism',
    price: 150,
    nibSize: 'Medium',
    startingPrice: 150,
    currentPrice: 150,
    image: 'https://www.pilotpen.eu/media/catalog/product/v/a/vanishing_point_black.jpg',
    status: 'ACTIVE',
  },
  {
    id: '15',
    brand: 'Kaweco',
    model: 'Sport',
    description: 'Pocket-sized pen with a retro design',
    price: 40,
    nibSize: 'Broad',
    startingPrice: 40,
    currentPrice: 40,
    image: 'https://www.kaweco-pen.com/35-large_default/kaweco-sport-fountain-pen-classic-black.jpg',
    status: 'ACTIVE',
  },
  {
    id: '16',
    brand: 'Sailor',
    model: 'Pro Gear',
    description: 'Japanese pen with a 21k gold nib',
    price: 200,
    nibSize: 'Medium',
    startingPrice: 200,
    currentPrice: 200,
    image: 'https://www.sailorpen.com/media/catalog/product/cache/6/image/800x800/9df78eab33525d08d6e5fb8d27136e95/s/a/sailor-pg-black.jpg',
    status: 'ACTIVE',
  },
  {
    id: '17',
    brand: 'Pilot',
    model: 'Custom 74',
    description: 'Transparent demonstrator pen with gold trim',
    price: 160,
    nibSize: 'Fine',
    startingPrice: 160,
    currentPrice: 160,
    image: 'https://www.pilot.co.jp/products/pen/fountain/custom/img/custom74_clear.jpg',
    status: 'ACTIVE',
  },
  {
    id: '18',
    brand: 'Platinum',
    model: 'Preppy',
    description: 'Affordable and reliable fountain pen',
    price: 10,
    nibSize: 'Medium',
    startingPrice: 10,
    currentPrice: 10,
    image: 'https://www.platinum-pen.co.jp/catalog/images/ptl-5000a-02.jpg',
    status: 'ACTIVE',
  },
  {
    id: '19',
    brand: 'TWSBI',
    model: '580 AL',
    description: 'Aluminum fountain pen with a piston filler',
    price: 70,
    nibSize: 'Broad',
    startingPrice: 70,
    currentPrice: 70,
    image: 'https://www.twsbi.com/bbs/board.php?bo_table=products&wr_id=29',
    status: 'ACTIVE',
  },
  {
    id: '20',
    brand: 'Pilot',
    model: 'Custom Heritage 92',
    description: 'Piston-filling demonstrator pen with a gold nib',
    price: 180,
    nibSize: 'Fine',
    startingPrice: 180,
    currentPrice: 180,
    image: 'https://www.pilot.co.jp/products/pen/fountain/ch92/img/ch92_clear.jpg',
    status: 'ACTIVE',
  },
  {
    id: '21',
    brand: 'Lamy',
    model: 'Dialog 3',
    description: 'Innovative retractable fountain pen',
    price: 280,
    nibSize: 'Medium',
    startingPrice: 280,
    currentPrice: 280,
    image: 'https://www.lamy.com/content/lamy_com/en/home/products/writing-instruments/fountain-pens/lamy-dialog-3/1200x630/dialog3_black_07.png',
    status: 'ACTIVE',
  },
  {
    id: '22',
    brand: 'Parker',
    model: 'Sonnet',
    description: 'Timeless pen with a stainless steel body',
    price: 120,
    nibSize: 'Fine',
    startingPrice: 120,
    currentPrice: 120,
    image: 'https://www.parkerpen.com/-/media/parker-pens/images/products/catalog/sonnet/sonnet-stainless-steel-gt-m.jpg',
    status: 'ACTIVE',
  },
  {
    id: '23',
    brand: 'Pelikan',
    model: 'M200',
    description: 'Classic fountain pen with a piston filler',
    price: 100,
    nibSize: 'Medium',
    startingPrice: 100,
    currentPrice: 100,
    image: 'https://www.pelikan.com/pulse/Pulsar/en_US.Store.displayImage.223424/pelikan-m200-pistong-fountain-pen.jpg',
    status: 'ACTIVE',
  },
  {
    id: '24',
    brand: 'Visconti',
    model: 'Rembrandt',
    description: 'Inspired by the famous painter',
    price: 140,
    nibSize: 'Broad',
    startingPrice: 140,
    currentPrice: 140,
    image: 'https://www.visconti.it/media/catalog/product/cache/3/image/9df78eab33525d08d6e5fb8d27136e95/r/e/rembrandt---varie-colorazioni_3.png',
    status: 'ACTIVE',
  },
  {
    id: '25',
    brand: 'Kaweco',
    model: 'AL Sport',
    description: 'Aluminum pocket-sized fountain pen',
    price: 80,
    nibSize: 'Fine',
    startingPrice: 80,
    currentPrice: 80,
    image: 'https://www.kaweco-pen.com/32-large_default/kaweco-al-sport-fountain-pen-aluminium.jpg',
    status: 'ACTIVE',
  },
  {
    id: '26',
    brand: 'Pilot',
    model: 'Custom Heritage 912',
    description: 'Elegant pen with a flexible gold nib',
    price: 250,
    nibSize: 'Medium',
    startingPrice: 250,
    currentPrice: 250,
    image: 'https://www.pilot.co.jp/products/pen/fountain/ch912/img/ch912_black.jpg',
    status: 'ACTIVE',
  },
  {
    id: '27',
    brand: 'Lamy',
    model: 'Studio',
    description: 'Contemporary pen with a distinctive clip design',
    price: 90,
    nibSize: 'Broad',
    startingPrice: 90,
    currentPrice: 90,
    image: 'https://www.lamy.com/content/lamy_com/en/home/products/writing-instruments/fountain-pens/lamy-studio/1200x630/studio_black_07.png',
    status: 'ACTIVE',
  },
  {
    id: '28',
    brand: 'Sailor',
    model: '1911',
    description: 'Classic pen with a gold nib',
    price: 220,
    nibSize: 'Fine',
    startingPrice: 220,
    currentPrice: 220,
    image: 'https://www.sailor.co.jp/products/fountainpen/img/fp1911_black.jpg',
    status: 'ACTIVE',
  },
  {
    id: '29',
    brand: 'Parker',
    model: 'Premier',
    description: 'Sophisticated pen with precious metal accents',
    price: 350,
    nibSize: 'Medium',
    startingPrice: 350,
    currentPrice: 350,
    image: 'https://www.parkerpen.com/-/media/parker-pens/images/products/catalog/premier/premier-metallic-ct-m.jpg',
    status: 'ACTIVE',
  },
  {
    id: '30',
    brand: 'Visconti',
    model: 'Van Gogh',
    description: 'Inspired by the famous painter',
    price: 180,
    nibSize: 'Broad',
    startingPrice: 180,
    currentPrice: 180,
    image: 'https://www.visconti.it/media/catalog/product/cache/3/image/9df78eab33525d08d6e5fb8d27136e95/v/i/van-gogh---varie-colorazioni_4.png',
    status: 'ACTIVE',
  },
  // Add more items here with the status attribute set to 'ACTIVE'
];









module.exports={PaintingList,FountainPens}; 
